### ISSUE TITLE
dr is nil

### ISSUE THREAD

**Issue by isSatake** [stkay/rubymotion-screenshot#1]
https://github.com/stkay/rubymotion-screenshot/blob/master/app/app_delegate.rb#L16 がうまくいってないっぽい 

![](http://gyazo.com/e30ad8b94a0fa69d6610f522c943a669.png)

**Comment by nikezono** [comment]
第四引数が`nil`なのがまずいのでは？

**Comment by keroxp** [comment]
普通にimgがnilなんじゃないの

**Comment by keroxp** [comment]
違った。drがnilなんだ

**Comment by nikezono** [comment]
> 違った。drがnilなんだ

ほんとだ : )

**Comment by isSatake** [comment]
fix d466d44fb02944f861b1fd91ffc95d1e135083d2
